cluster.name: "mycluster"
network.host: 0.0.0.0


node.master: true

xpack.license.self_generated.type: trial
#xpack.security.enabled: true
xpack.monitoring.collection.enabled: true

discovery.zen.ping.unicast.hosts: ["127.0.0.1:9200"]
node.name: "elasticsearch"
cluster.initial_master_nodes: "elasticsearch"

