version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml    
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: "changeme"
      cluster.name: "mycluster"
      node.name: "elasticsearch"
      node.master: "true"
      cluster.initial_master_nodes: "elasticsearch"
      discovery.zen.ping.unicast.hosts: "elasticsearch"
      discovery.zen.minimum_master_nodes: 1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.role == manager
  

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    ports:
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf    
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.role == worker

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
      placement:
         constraints: 
          - node.role == manager

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  kibana_config:
    file: ./kibana/config/kibana.yml
